blockExoticSubdeps: false # TODO: Enable after upgrading to Electron Forge 8
minimumReleaseAge: 10080
nodeLinker: hoisted
trustPolicy: no-downgrade
trustPolicyExclude:
  - undici-types@6.21.0
  - semver@6.3.1
  - chokidar@4.0.3

minimumReleaseAgeExclude:
  - "@pnpm/exe.android-arm64@12.8.1"
  - "@pnpm/exe.android-x64@12.8.1"
  - "@pnpm/exe.darwin-arm64@12.8.1"
  - "@pnpm/exe.darwin-x64@12.8.1"
  - "@pnpm/exe.freebsd-x64@12.8.1"
  - "@pnpm/exe.linux-arm64-musl@12.8.1"
  - "@pnpm/exe.linux-arm64@12.8.1"
  - "@pnpm/exe.linux-ppc64@12.8.1"
  - "@pnpm/exe.linux-riscv64@12.8.1"
  - "@pnpm/exe.linux-s390x@12.8.1"
  - "@pnpm/exe.linux-x64-musl@12.8.1"
  - "@pnpm/exe.linux-x64@12.8.1"
  - "@pnpm/exe.win32-arm64@12.8.1"
  - "@pnpm/exe.win32-x64@12.8.1"
  - "pnpm@12.8.1"

packages:
  - "packages/*"

allowedDeprecatedVersions:
  eslint: "9"

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  electron: true
  esbuild: true
  modern-ahocorasick: true

update:
  githubActions: true
