import path from "path";
import {
  app,
  BrowserWindow,
  Menu,
  nativeTheme,
  MenuItem,
  ipcMain,
  shell,
} from "electron";
import { t } from "i18next";
import { darkPalette, lightPalette } from "./theme/color";
import "./i18n.main";
import { IpcEventType } from "./ipc";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

let fullscreen = false;
let focused = false;

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    backgroundColor: nativeTheme.shouldUseDarkColors
      ? darkPalette.surface.surface
      : lightPalette.surface.surface,
    titleBarStyle: "hiddenInset",
    trafficLightPosition: { x: 20, y: 18 },
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

  mainWindow.on("enter-full-screen", () => {
    fullscreen = true;
    createApplicationMenu();
  });

  mainWindow.on("leave-full-screen", () => {
    fullscreen = false;
    createApplicationMenu();
  });

  mainWindow.on("focus", () => {
    focused = true;
    createApplicationMenu();
  });

  mainWindow.on("closed", () => {
    focused = false;
    createApplicationMenu();
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }
};

let sidebarOpen = true;

/**
 * Creates application menu items.
 *
 * @see https://www.electronjs.org/docs/latest/api/menu#examples
 */
const createApplicationMenu = () => {
  const devToolsEnabled = false;

  const onToggleSidebar = (
    _: MenuItem,
    focusedWindow: BrowserWindow | undefined,
  ) => {
    sidebarOpen = !sidebarOpen;
    createApplicationMenu();
    focusedWindow?.webContents.send(IpcEventType.ToggleSidebar, sidebarOpen);
  };

  const menuTemplate: Electron.MenuItemConstructorOptions[] = [
    {
      label: "",
      submenu: [
        {
          label: t("applicationMenu.about"),
          role: "about",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.services"),
          role: "services",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.hide"),
          role: "hide",
        },
        {
          label: t("applicationMenu.hideOthers"),
          role: "hideOthers",
        },
        {
          label: t("applicationMenu.unhide"),
          role: "unhide",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.quit"),
          role: "quit",
        },
      ],
    },
    {
      label: t("applicationMenu.file"),
      submenu: [
        // 最近の漢字
        {
          label: t("Sidebar.recentlyStudied"),
          accelerator: "Command+1",
          click: (_, focusedWindow) =>
            focusedWindow?.webContents.send(IpcEventType.Navigate, "/"),
        },
        // TODO: Get books from store
        {
          label: "常用漢字",
          accelerator: "Command+2",
          click: (_, focusedWindow) =>
            focusedWindow?.webContents.send(IpcEventType.Navigate, "/books/1"),
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.close"),
          role: "close",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.shareMenu"),
          role: "shareMenu",
          sharingItem: undefined,
        },
      ],
    },
    {
      label: t("applicationMenu.edit"),
      submenu: [
        {
          label: t("applicationMenu.undo"),
          role: "undo",
        },
        {
          label: t("applicationMenu.redo"),
          role: "redo",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.cut"),
          role: "cut",
        },
        {
          label: t("applicationMenu.copy"),
          role: "copy",
        },
        {
          label: t("applicationMenu.paste"),
          role: "paste",
        },
        {
          label: t("applicationMenu.pasteAndMatchStyle"),
          role: "pasteAndMatchStyle",
        },
        {
          label: t("applicationMenu.selectAll"),
          role: "selectAll",
        },
      ],
    },
    {
      label: t("applicationMenu.view"),
      submenu: [
        {
          id: "toggleSidebar",
          label: sidebarOpen
            ? t("applicationMenu.hideSidebar")
            : t("applicationMenu.showSidebar"),
          accelerator: "Command+Shift+L",
          enabled: focused,
          click: onToggleSidebar,
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.resetZoom"),
          role: "resetZoom",
        },
        {
          label: t("applicationMenu.zoomIn"),
          role: "zoomIn",
        },
        {
          label: t("applicationMenu.zoomOut"),
          role: "zoomOut",
        },
        {
          type: "separator",
        },
        {
          label: fullscreen
            ? t("applicationMenu.leaveFullscreen")
            : t("applicationMenu.enterFullscreen"),
          role: "togglefullscreen",
        },
      ],
    },
    {
      id: "window",
      label: t("applicationMenu.window"),
      role: "window",
      submenu: [
        {
          label: t("applicationMenu.minimize"),
          role: "minimize",
        },
        {
          label: t("applicationMenu.zoom"),
          role: "zoom",
        },
      ],
    },
    {
      label: t("applicationMenu.help"),
      role: "help",
      submenu: [
        {
          label: t("applicationMenu.reportIssue"),
          click: () =>
            shell.openExternal("https://github.com/vvornanen/aoboshi/issues"),
        },
      ],
    },
  ];

  if (devToolsEnabled) {
    menuTemplate.push({
      label: t("applicationMenu.develop"),
      before: ["window"],
      submenu: [
        {
          label: t("applicationMenu.reload"),
          role: "reload",
        },
        {
          type: "separator",
        },
        {
          label: t("applicationMenu.toggleDevTools"),
          role: "toggleDevTools",
        },
      ],
    });
  }

  const menu = Menu.buildFromTemplate(menuTemplate);
  Menu.setApplicationMenu(menu);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createApplicationMenu();
  createWindow();

  ipcMain.on(IpcEventType.ToggleSidebar, (_, value) => {
    sidebarOpen = value;
    createApplicationMenu();
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
