import path from "path";
import { app, BrowserWindow, nativeTheme, ipcMain } from "electron";
import { darkPalette, lightPalette } from "./theme/color";
import "./i18n.main";
import { IpcEventType } from "./ipc";
import { ApplicationMenu } from "./mainProcess/ApplicationMenu";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

const applicationMenu = new ApplicationMenu({
  sidebarOpen: true,
  devToolsEnabled: true,
  mainWindowFocused: false,
  fullscreen: false,
});

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    backgroundColor: nativeTheme.shouldUseDarkColors
      ? darkPalette.surface.surface
      : lightPalette.surface.surface,
    titleBarStyle: "hiddenInset",
    trafficLightPosition: { x: 20, y: 18 },
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

  mainWindow.on("enter-full-screen", () => {
    applicationMenu.fullscreen = true;
  });

  mainWindow.on("leave-full-screen", () => {
    applicationMenu.fullscreen = false;
  });

  mainWindow.on("focus", () => {
    applicationMenu.mainWindowFocused = true;
  });

  mainWindow.on("closed", () => {
    applicationMenu.mainWindowFocused = false;
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  applicationMenu.update();
  createWindow();

  ipcMain.on(IpcEventType.ToggleSidebar, (_, value) => {
    applicationMenu.sidebarOpen = value;
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
