import { StyleRule, layer } from "@vanilla-extract/css";

// Composing CSS styles generated by vanilla-extract can easily cause precedence
// issues because all the styles have the same precedence, so therefore changing
// styles import order may cause unexpected side effects.
// CSS cascade layers ensure that all reset styles always have the lowest
// precedence, and all non-reusable component styles on the default layer will
// always override reusable styles on the common layer.

// The order of these variables defines the layers' precedence
const reset = layer();
const typography = layer();
const icons = layer();
const common = layer();

type LayerStyleRule = Omit<StyleRule, "@layer">;

const withLayer = (layer: string, style: LayerStyleRule): StyleRule => ({
  "@layer": {
    [layer]: style,
  },
});

export const resetLayer = (style: LayerStyleRule) => withLayer(reset, style);
export const typographyLayer = (style: LayerStyleRule) =>
  withLayer(typography, style);
export const iconsLayer = (style: LayerStyleRule) => withLayer(icons, style);
export const commonLayer = (style: LayerStyleRule) => withLayer(common, style);
