import { BrowserWindow, nativeTheme } from "electron";
import path from "path";
import { darkPalette, lightPalette } from "../renderer/theme/color";
import { ApplicationContext } from "./ApplicationContext";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

export class MainWindow {
  private window: BrowserWindow;

  constructor(context: ApplicationContext) {
    this.window = new BrowserWindow({
      width: 1000,
      height: 600,
      backgroundColor: nativeTheme.shouldUseDarkColors
        ? darkPalette.surface.surface
        : lightPalette.surface.surface,
      titleBarStyle: "hiddenInset",
      trafficLightPosition: { x: 20, y: 18 },
      webPreferences: {
        preload: path.join(__dirname, "preload.js"),
      },
    });

    this.window.on("enter-full-screen", () => {
      context.applicationMenu.fullscreen = true;
    });

    this.window.on("leave-full-screen", () => {
      context.applicationMenu.fullscreen = false;
    });

    this.window.on("focus", () => {
      context.applicationMenu.mainWindowFocused = true;
    });

    this.window.on("closed", () => {
      context.applicationMenu.mainWindowFocused = false;
    });

    // and load the index.html of the app.
    if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
      this.window.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
    } else {
      this.window.loadFile(
        path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
      );
    }
  }
}
